services:
  nginx:
    depends_on:
      - mattermost
    container_name: nginx_mattermost
    image: nginx:${NGINX_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d:ro
      - ${NGINX_DHPARAMS_FILE}:/dhparams4096.pem
      - ${CERT_PATH}:/cert.pem:ro
      - ${KEY_PATH}:/key.pem:ro
      - shared-webroot:/usr/share/nginx/html
    environment:
      # timezone inside container
      - TZ
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
  mattermost:
    ports:
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp

  certbot-renew:
    image: certbot/certbot
    restart: ${RESTART_POLICY}
    profiles: ["acme"]
    depends_on:
      - nginx
    ## Required to reload nginx via kill -HUP 1
    pid: "service:nginx"
    volumes:
      - ./certs/etc/letsencrypt:/etc/letsencrypt
      - ./certs/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certs/var/log/letsencrypt:/var/log/letsencrypt
      - shared-webroot:/webroot
    environment:
      - DOMAIN=${DOMAIN}
    entrypoint: |
      sh -c "
        while true; do
          certbot renew --cert-name $DOMAIN --webroot-path /webroot --deploy-hook 'kill -HUP 1';
          echo 'Sleeping 24h...';
          sleep 24h;
        done
      "

  certbot-init:
    image: certbot/certbot
    profiles: ["acme-init"]
    volumes:
      - ./certs/etc/letsencrypt:/etc/letsencrypt
      - ./certs/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certs/var/log/letsencrypt:/var/log/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    entrypoint: |
      sh -c "
        if [ -d /etc/letsencrypt/live/$DOMAIN ]; then
          echo 'Certificate already exists for $DOMAIN';
          exit 0;
        fi;
        certbot certonly --standalone --http-01-port $HTTP_PORT -d $DOMAIN --register-unsafely-without-email --agree-tos --non-interactive;
      "

# Shared volume for Let's Encrypt certificate renewal with a webroot
volumes:
  shared-webroot:
    name: shared-webroot

# This network name is being used for Let's Encrypt certificate renewal
networks:
  default:
    name: mattermost
